Import necessary libraries.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Load our data

In [2]:
df = pd.read_excel(r"C:\Users\Lokey\Desktop\lucy\Weather_Data.xlsx")
df.head()

Outlook Temperature Humidity  Windy Play Golf
0     Rainy         Hot     High   True        No
1     Rainy         Hot     High   True       Yes
2  Overcast         Hot     High  False       Yes
3     Sunny        Mild     High  False       Yes
4     Sunny        Cool   Normal  False        No

In [3]:
df.shape

(14, 5)

## Table Value Options

In [4]:
Outlook = ['Rainy', 'Overcast', 'Sunny']
Temperature = ['Hot', 'Mild','Cool']
Humidity = ['High','Normal']
Windy = ['True', 'False'] #might not work with string
PlayGolf = ['Yes','No']

## Order Table by Temperature - Calculate based on Temperature

In [5]:
#might have to change this..is this the column that it refers to?
df_temp_Hot = df.loc[df['Temperature'] == 'Hot']
df_temp_Hot = df_temp_Hot.reset_index(drop=True)

df_temp_Mild = df.loc[df['Temperature'] == 'Mild']
df_temp_Mild = df_temp_Mild.reset_index(drop=True)

df_temp_Cool = df.loc[df['Temperature'] == 'Cool']
df_temp_Cool = df_temp_Cool.reset_index(drop=True)

df_Temp = [df_temp_Hot, df_temp_Mild, df_temp_Cool]
df_Temp[0] #arrays start from index 0

Outlook Temperature Humidity  Windy Play Golf
0     Rainy         Hot     High   True        No
1     Rainy         Hot     High   True       Yes
2  Overcast         Hot     High  False       Yes
3  Overcast         Hot   Normal  False       Yes

In [6]:
for nn in range(2):
    temp_data = []
    label = Outlook[nn]
    
    for n in range(3): #Table Value Options
        xx = []
        df_temp = df_Temp[n]
        val_temperature = Temperature[n]# refs table value option
        
        #df_temp['whatever'] references column in excel sheet
        #i - references your row in excel sheet
        for i in range(len(df_temp)):
            x = int((df_temp['Temperature'][i] == val_temperature and df_temp['Outlook'][i] == label))
            xx = np.append(xx,x) #adds
            xxx = sum(xx)
            
        temp_data = np.append(temp_data, xxx) #add
    
    prob_temp = (temp_data/sum(temp_data)).reshape(3,1) #calculates probability
    
    if nn == 0:
        prob_Temp = prob_temp
    if nn == 1:
        prob_Temp = [prob_Temp, prob_temp] 
prob_Temp

[array([[0.4],
        [0.4],
        [0.2]]),
 array([[0.5 ],
        [0.25],
        [0.25]])]

## Order Table by Humidity - Calculate based on Humidity

In [7]:
df_humidity_high = df.loc[df['Humidity'] == 'High']
df_humidity_high = df_humidity_high.reset_index(drop=True)

df_humidity_normal = df.loc[df['Humidity'] == 'Normal']
df_humidity_normal = df_humidity_normal.reset_index(drop=True)

df_Humidity = [df_humidity_high, df_humidity_normal]
df_Humidity[0]

Outlook Temperature Humidity  Windy Play Golf
0     Rainy         Hot     High   True        No
1     Rainy         Hot     High   True       Yes
2  Overcast         Hot     High  False       Yes
3     Sunny        Mild     High  False       Yes
4     Rainy        Mild     High  False       Yes
5  Overcast        Mild     High   True       Yes
6     Sunny        Mild     High   True        No

In [8]:
for nn in range(2):
    humidity_data = []
    label = Outlook[nn]
    
    for n in range(2): #Table Value Options
        xx = []
        df_humidity = df_Humidity[n]
        val_humidity = Humidity[n]
        
        for i in range(len(df_humidity)):
            x = int((df_humidity['Humidity'][i] == val_humidity and df_humidity['Outlook'][i] == label))
            xx = np.append(xx,x)
            xxx = sum(xx)
            
        humidity_data = np.append(humidity_data, xxx)
        
    prob_humidity = (humidity_data/sum(humidity_data)).reshape(2,1)
    
    if nn == 0:
        prob_Humidity = prob_humidity
    if nn == 1:
        prob_Humidity = [prob_Humidity, prob_humidity]
prob_Humidity        

[array([[0.6],
        [0.4]]),
 array([[0.5],
        [0.5]])]

## Order Table by Windy - Calculate based on Windy

In [9]:
df_windy_true = df.loc[df['Windy'] == 'True']
df_windy_true = df_windy_true.reset_index(drop=True)

df_windy_false = df.loc[df['Windy'] == 'False']
df_windy_false = df_windy_false.reset_index(drop=True)

df_Windy = [df_windy_false, df_windy_true]
df_Windy[1] 
#table not displaying

Empty DataFrame
Columns: [Outlook, Temperature, Humidity, Windy, Play Golf]
Index: []

In [10]:
for nn in range(2):
    windy_data= []
    label = Outlook[nn]
    
    for n in range(2):
        xx = []
        df_windy = df_Windy[n]
        wind = Windy[n]
        
        for i in range(len(df_windy)):
            x = int((df_windy['Windy'][i] == wind and df_windy['Outlook'][i] == label))
            xx = np.append(xx, x)
            xxx = sum(xx)
            
        windy_data = np.append(windy_data,xxx)
        
    prob_windy = (windy_data/sum(windy_data)).reshape(2,1)
    
    if nn == 0:
        prob_Windy = prob_windy
    if nn == 1:
        prob_Windy = [prob_Windy, prob_windy]
prob_Windy

[array([[0.5],
        [0.5]]),
 array([[0.5],
        [0.5]])]

## Calculate Probability of Outlook

In [11]:
prob_outlook_rainy = sum((df['Outlook'] == 'Rainy').to_numpy())/len(df)
prob_outlook_overcast = sum((df['Outlook'] == 'Overcast').to_numpy())/len(df)
prob_outlook_sunny = sum((df['Outlook'] == 'Sunny').to_numpy())/len(df)

## Actual Prediction

In [12]:
Outlook = ['Rainy', 'Overcast', 'Sunny']
Temperature = ['Hot', 'Mild','Cool']
Humidity = ['High','Normal']
Windy = ['True', 'False'] #might not work with string
PlayGolf = ['Yes','No'] 

#user-input
#a1 = Outlook.index(input('Outlook for the day: '))
a2 = Temperature.index(input('Temperature for the day: '))
a3 = Humidity.index(input('Humidity for the day: '))
a4 = Windy.index(input('Wind for the day: '))

Temperature for the day: Mild
Humidity for the day: High
Wind for the day: True


## Request user-input

In [13]:
Likelihood_rainy = prob_outlook_rainy * prob_Temp[0][a2] * prob_Humidity[0][a3] * prob_Windy[0][a4]
Likelihood_sunny = prob_outlook_sunny * prob_Temp[1][a2] * prob_Humidity[1][a3] * prob_Windy[1][a4]

#Likelihood_overcast = prob_outlook_overcast * prob_Outlook[1][a1] * prob_Temp[1][a2] * prob_Humidity[1][a3] * prob_Windy[1][a4]

if(Likelihood_rainy > Likelihood_sunny):
    print('The likelihood that rain will fall is HIGH. Rainy outlook.')
else:
    print('The likelihood that rain will fall is Low. Sunny outlook.')
    
#Error produced whenusing three Likelihoods

#if ((Likelihood_rainy > Likelihood_overcast)and(Likelihood_rainy > Likelihood_sunny)): 
#    print('The likelihood that rain will fall is HIGH. Rainy outlook.')
#elif((Likelihood_overcast > Likelihood_rainy)and(Likelihood_overcast > Likelihood_sunny)):
#    print('The likelihood that rain will fall is MEDIUM. Overcast outlook.')
#elif((Likelihood_sunny > likelihood_rainy)and(Likelihood_sunny > Likelihood_overcast)):
#    print('The likelihood that rain will fall is LOW. Sunny outlook.')

The likelihood that rain will fall is HIGH. Rainy outlook.
